# Generated by Django 2.2.14 on 2020-07-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('tittle', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('editorial', models.CharField(max_length=50)),
            ],
        ),
    ]
