# Generated by Django 2.2.14 on 2020-07-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('web', models.CharField(max_length=50)),
            ],
        ),
    ]
